name: Renovate
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - beta-44
    paths:
      - '.github/renovate.json5'
      - '.github/workflows/renovate.yml'

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6 # v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.14
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: 'debug'
